/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PatientDemographics = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'breed' : IDL.Text,
  'species' : IDL.Text,
});
export const Time = IDL.Int;
export const TaskItem = IDL.Record({
  'checked' : IDL.Bool,
  'required' : IDL.Bool,
});
export const TasksChecklist = IDL.Record({
  'pdvmNotified' : TaskItem,
  'histo' : TaskItem,
  'labs' : TaskItem,
  'culture' : TaskItem,
  'surgeryReport' : TaskItem,
  'imaging' : TaskItem,
  'dischargeNotes' : TaskItem,
});
export const SurgeryCase = IDL.Record({
  'arrivalDate' : Time,
  'medicalRecordNumber' : IDL.Text,
  'isSynchronized' : IDL.Bool,
  'lastSyncTimestamp' : Time,
  'caseId' : IDL.Nat,
  'tasksChecklist' : TasksChecklist,
  'patientDemographics' : PatientDemographics,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SurgeryCaseUpdate = IDL.Record({
  'arrivalDate' : IDL.Opt(Time),
  'medicalRecordNumber' : IDL.Opt(IDL.Text),
  'tasksChecklist' : IDL.Opt(TasksChecklist),
  'patientDemographics' : IDL.Opt(PatientDemographics),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSurgeryCase' : IDL.Func(
      [IDL.Text, PatientDemographics, Time, TasksChecklist],
      [IDL.Nat],
      [],
    ),
  'getAllSurgeryCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUpdatedCases' : IDL.Func([Time], [IDL.Vec(SurgeryCase)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUnsyncedChanges' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'syncLocalChanges' : IDL.Func([IDL.Vec(SurgeryCase)], [], []),
  'updateSurgeryCase' : IDL.Func([IDL.Nat, SurgeryCaseUpdate], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PatientDemographics = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'breed' : IDL.Text,
    'species' : IDL.Text,
  });
  const Time = IDL.Int;
  const TaskItem = IDL.Record({ 'checked' : IDL.Bool, 'required' : IDL.Bool });
  const TasksChecklist = IDL.Record({
    'pdvmNotified' : TaskItem,
    'histo' : TaskItem,
    'labs' : TaskItem,
    'culture' : TaskItem,
    'surgeryReport' : TaskItem,
    'imaging' : TaskItem,
    'dischargeNotes' : TaskItem,
  });
  const SurgeryCase = IDL.Record({
    'arrivalDate' : Time,
    'medicalRecordNumber' : IDL.Text,
    'isSynchronized' : IDL.Bool,
    'lastSyncTimestamp' : Time,
    'caseId' : IDL.Nat,
    'tasksChecklist' : TasksChecklist,
    'patientDemographics' : PatientDemographics,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SurgeryCaseUpdate = IDL.Record({
    'arrivalDate' : IDL.Opt(Time),
    'medicalRecordNumber' : IDL.Opt(IDL.Text),
    'tasksChecklist' : IDL.Opt(TasksChecklist),
    'patientDemographics' : IDL.Opt(PatientDemographics),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSurgeryCase' : IDL.Func(
        [IDL.Text, PatientDemographics, Time, TasksChecklist],
        [IDL.Nat],
        [],
      ),
    'getAllSurgeryCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUpdatedCases' : IDL.Func([Time], [IDL.Vec(SurgeryCase)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUnsyncedChanges' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'syncLocalChanges' : IDL.Func([IDL.Vec(SurgeryCase)], [], []),
    'updateSurgeryCase' : IDL.Func(
        [IDL.Nat, SurgeryCaseUpdate],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };