/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PatientDemographics {
  'age' : bigint,
  'name' : string,
  'breed' : string,
  'species' : string,
}
export interface SurgeryCase {
  'arrivalDate' : Time,
  'medicalRecordNumber' : string,
  'isSynchronized' : boolean,
  'lastSyncTimestamp' : Time,
  'caseId' : bigint,
  'tasksChecklist' : TasksChecklist,
  'patientDemographics' : PatientDemographics,
}
export interface SurgeryCaseUpdate {
  'arrivalDate' : [] | [Time],
  'medicalRecordNumber' : [] | [string],
  'tasksChecklist' : [] | [TasksChecklist],
  'patientDemographics' : [] | [PatientDemographics],
}
export interface TaskItem { 'checked' : boolean, 'required' : boolean }
export interface TasksChecklist {
  'pdvmNotified' : TaskItem,
  'histo' : TaskItem,
  'labs' : TaskItem,
  'culture' : TaskItem,
  'surgeryReport' : TaskItem,
  'imaging' : TaskItem,
  'dischargeNotes' : TaskItem,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSurgeryCase' : ActorMethod<
    [string, PatientDemographics, Time, TasksChecklist],
    bigint
  >,
  'getAllSurgeryCases' : ActorMethod<[], Array<SurgeryCase>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUpdatedCases' : ActorMethod<[Time], Array<SurgeryCase>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUnsyncedChanges' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'syncLocalChanges' : ActorMethod<[Array<SurgeryCase>], undefined>,
  'updateSurgeryCase' : ActorMethod<[bigint, SurgeryCaseUpdate], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];